### ISSUE TITLE
Version for ESP32

### ISSUE THREAD

**Issue by AcuarioCat** [khoih-prog/AsyncWebServer_Ethernet#1]
I see this is only ESP8266 and your version for ESP32 is only for the Ethernet PHY boards.
Do you plan on an ESP32 version to work with the SPI boards (such as ENC28J60)?

Why ?
From what I can see the Ethernet PHY using the LAN8720 takes up 10 GPIO ports which is somewhat excessive. I haven't tried but I'm assuming these can't be shared with other peripherals.

Using an SPI board only 4 GPIO ports are needed with 3 of these being shared SPI and 1 is optional (as it can be the EN of the ESP32). In a shared SPI configuration using EN this can actually reduce the count to just 1 for the enable.

**Comment by khoih-prog** [comment]
> Do you plan on an ESP32 version to work with the SPI boards (such as ENC28J60)?

Not until any Ethernet library for W5x00, ENC28J60, etc. is **rewritten to use LwIP**, such as [**lwIP_w5100**](https://github.com/esp8266/Arduino/tree/master/libraries/lwIP_w5100). Sorry I don't have time to do all of these now.

**Hopefully someone will chip in and help** to rewrite those general-purpose lwip-based Ethernet libraries, then Async can be used for any core / board.
