### ISSUE TITLE
regex not working

### ISSUE THREAD

**Issue by MYBLtd** [khoih-prog/AsyncWebServer_Ethernet#2]
The example file Async_RegexPatterns is not working for me: the / is working, but /sensors/0 gets me the 404 not found response.
I am using the <ETH.h> library on a Olimex esp32-evb board.

I added compiler.cpp.extra_flags=-DASYNCWEBSERVER_REGEX=1 to the file /Library/Arduino15/packages/esp32/hardware/esp32/2.0.4/platform.txt

**Comment by khoih-prog** [comment]
Hi @MYBLtd 

Please follow guideline in creating issue, such as [**Minimal, Reproducible Example**](https://stackoverflow.com/help/minimal-reproducible-example) as well as more info about **board, core, full code**, etc.

As this example is based on [**regex_patterns** example](https://github.com/me-no-dev/ESPAsyncWebServer/tree/master/examples/regex_patterns) of [**ESPAsyncWebServer** library](https://github.com/me-no-dev/ESPAsyncWebServer), I suggest you try it to see if issue is with your code, server, etc. It same problem, post the issue [**there**](https://github.com/me-no-dev/ESPAsyncWebServer) to have it fixed.

I'm closing the issue now and won't reopen until you follow the guideline or prove there is a bug of this library.

Good Luck,
